;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;   https://github.com/polybar/polybar
;
;==========================================================

[colors]
background = #282A2E
background-alt = #373B41
foreground = #C5C8C6
primary = #1da5d4
secondary = #8ABEB7
alert = #e31b1b
disabled = #707880
positive = #BAE35B
black = #000000
white = #FFFFFF
; Basic colors, mostly for testing
basicblue = #0000FF
basicred = #FF0000
basicgreen = #00FF00
basicyellow = #FFFF00
basicorange = #FF6600
basicpurple = #6600FF

[bar/main]
width = 100%
height = 24pt
radius = 6

; dpi = 96

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 3pt

border-size = 4pt
border-color = #00000000

padding-left = 0
padding-right = 1

module-margin = 1

separator = │
separator-font = 3
separator-foreground = ${colors.disabled}

font-0 = "JetBrainsMono Regular:size=12;2"
font-1 = "JetBrainsMono Nerd Font Mono:size=22;5"

; Fonts used for specific items
font-2 = "JetBrainsMono Nerd Font Mono:size=16;4"
font-3 = "JetBrainsMono Nerd Font Mono:size=24;5"
font-4 = "JetBrainsMono Nerd Font Mono:size=16;3"
;	Battery lightning bolt
font-5 = "JetBrainsMono Nerd Font Mono:size=14;5"

modules-left = xworkspaces i3 xwindow
modules-right = filesystem pulseaudio xkeyboard memory cpu battery wlan eth date

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true

; tray-position = right

; wm-restack = generic
; wm-restack = bspwm
; wm-restack = i3

; override-redirect = true

[module/xworkspaces]
type = internal/xworkspaces

; Functionality/Interaction
enable-click = false

; Labels and looks
label-active = %icon%
label-active-background = ${colors.background-alt}
label-active-underline= ${colors.primary}
label-active-padding = 2

label-occupied = %icon%
label-occupied-padding = 2

label-urgent = %icon%
label-urgent-background = ${colors.alert}
label-urgent-padding = 2

label-empty = %icon%
label-empty-foreground = ${colors.disabled}
label-empty-padding = 2

; Icons
icon-0 = 1;
icon-1 = 2;
icon-2 = 3;
icon-3 = 4;4
icon-4 = 5;5
icon-5 = 6;拾
icon-6 = 7;7
icon-7 = 8;8
icon-8 = 9;9
icon-9 = 10;10
icon-default = 

[module/i3]
type = internal/i3
format = <label-mode>
label-mode = %mode%
label-mode-padding = 2
label-mode-background = #e60053

[module/xwindow]
type = internal/xwindow
label = %title:0:50:...%
label-maxlen = 50

[module/filesystem]
type = internal/fs
interval = 25

mount-0 = /

label-mounted = %{F#1da5d4} %mountpoint%%{F-} %percentage_used%%

label-unmounted = %mountpoint% not mounted
label-unmounted-foreground = ${colors.disabled}

[module/pulseaudio]
type = internal/pulseaudio

format-volume-prefix = "VOL "
format-volume-prefix-foreground = ${colors.primary}
format-volume = <label-volume>

label-volume = %percentage%%

label-muted = muted
label-muted-foreground = ${colors.disabled}

[module/memory]
type = internal/memory
interval = 2
format = ""

; Make memory usage only appear when it goes above 60%
warn-percentage = 60
format-warn = <label-warn>
format-warn-prefix = " "
format-warn-prefix-foreground = ${colors.alert}
label-warn = %percentage_used:2%%

[module/cpu]
type = internal/cpu
interval = 2
format = ""

; Make cpu usage only appear when it goes above 50%
warn-percentage = 50
format-warn = <label-warn>
format-warn-prefix = ""
format-warn-prefix-foreground = ${colors.alert}
label-warn = %percentage:2%%

[network-base]
type = internal/network
interval = 5
format-connected = <label-connected>
format-disconnected = <label-disconnected>
label-disconnected = %{F#1da5d4}%{F#707880}

[module/wlan]
inherit = network-base
interface-type = wireless
label-connected = %{F#1da5d4}%{F-} %essid% %local_ip%

[module/eth]
inherit = network-base
interface-type = wired
label-connected = %{F#1da5d4}%{F-} %local_ip%

[module/date]
type = internal/date
interval = 1

date = %H:%M:%S
date-alt = %Y-%m-%d %H:%M:%S

label = %date%
label-foreground = ${colors.primary}

[settings]
screenchange-reload = true
pseudo-transparency = true

; vim:ft=dosini